//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace VidyanoStarterKit.Service
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VidyanoStarterKitEntityModelContainer : Vidyano.Service.TargetObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VidyanoStarterKitEntityModelContainer object using the connection string found in the 'VidyanoStarterKitEntityModelContainer' section of the application configuration file.
        /// </summary>
        public VidyanoStarterKitEntityModelContainer() : base("name=VidyanoStarterKitEntityModelContainer", "VidyanoStarterKitEntityModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VidyanoStarterKitEntityModelContainer object.
        /// </summary>
        public VidyanoStarterKitEntityModelContainer(string connectionString) : base(connectionString, "VidyanoStarterKitEntityModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VidyanoStarterKitEntityModelContainer object.
        /// </summary>
        public VidyanoStarterKitEntityModelContainer(EntityConnection connection) : base(connection, "VidyanoStarterKitEntityModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
